/* Generated by scripts/build-mini-games.mjs from source.js. Do not edit. */
/* Radio repair v2: three-stage, mechanics-first replacement. */
(function () {
	"use strict";

	const WIDTH = 1000;
	const HEIGHT = 560;
	const TAU = Math.PI * 2;
	const COLORS = {
		ink: "#090604",
		panel: "#1b120c",
		panel2: "#2a1b10",
		edge: "#815029",
		metal: "#9a6332",
		light: "#e0bd79",
		dim: "#a07a4e",
		amber: "#cf8435",
		green: "#82916b",
		red: "#965344"
	};
	const TUNING_CONTROLS = {
		coarse: { x: 245, y: 367, hitRadius: 82, min: 0, max: 1, valuePerRadian: .06, angleKey: "coarseKnobAngle" },
		fine: { x: 830, y: 395, hitRadius: 58, min: -.12, max: .12, valuePerRadian: .018, angleKey: "fineKnobAngle" }
	};
	const TUNING_QUALITY = {
		coarseWeight: 3.1,
		fineWeight: 7.2,
		responsePerSecond: 2.8
	};

	function clamp(value, min, max) {
		return Math.max(min, Math.min(max, value));
	}

	function normalizeAngle(angle) {
		return Math.atan2(Math.sin(angle), Math.cos(angle));
	}

	function shortestAngleDelta(next, previous) {
		return normalizeAngle(next - previous);
	}

	function knobRotationFromNormalized(normalized) {
		return -2.25 + normalized * 4.5;
	}

	function distance(a, b) {
		return Math.hypot(a.x - b.x, a.y - b.y);
	}

	function pointInRect(point, rect) {
		return point.x >= rect.x && point.x <= rect.x + rect.w && point.y >= rect.y && point.y <= rect.y + rect.h;
	}

	function pointInCircle(point, circle) {
		return Math.hypot(point.x - circle.x, point.y - circle.y) <= circle.r;
	}

	function phaseTask(phase) {
		return {
			inspect: "检查收音机故障",
			gears: "修复齿轮传动",
			tune: "调整频率并稳定信号",
			complete: "维修完成"
		}[phase] || "检查收音机故障";
	}

	function phaseGuide(phase) {
		return {
			inspect: "点击各部件查看状态，找出故障位置",
			gears: "让相邻齿数之和接近轴距，绿线会继续传动",
			tune: "调节主频和微调，直到信号格全部亮起",
			complete: "信号稳定，收音机已恢复工作"
		}[phase] || "";
	}

	function createRadioRepair(root, options) {
		const config = Object.assign({ embedded: true, muted: false, onEvent: null }, options || {});
		root.replaceChildren();

		const shell = document.createElement("main");
		shell.className = "radio-repair-shell" + (config.embedded ? " is-embedded" : "");
		shell.innerHTML = [
			'<aside class="rr-task" role="status" aria-live="polite">',
			'<h1 class="rr-task__text">检查收音机故障</h1>',
			'<p class="rr-task__guide"></p>',
			'<p class="rr-task__hint" hidden></p>',
			'</aside>',
			'<section class="rr-stage" aria-label="收音机维修区域">',
			'<canvas class="rr-canvas" width="1000" height="560" role="img" aria-label="收音机维修台"></canvas>',
			'</section>',
			'<div class="rr-sr-only" aria-live="polite"></div>'
		].join("");
		root.appendChild(shell);

		const canvas = shell.querySelector(".rr-canvas");
		const ctx = canvas.getContext("2d");
		const taskText = shell.querySelector(".rr-task__text");
		const guideText = shell.querySelector(".rr-task__guide");
		const hintText = shell.querySelector(".rr-task__hint");
		const live = shell.querySelector(".rr-sr-only");

		const inspectParts = {
			speaker: { x: 230, y: 290, r: 94 },
			wires: { x: 345, y: 385, w: 230, h: 66 },
			knob: { x: 765, y: 365, r: 60 },
			pointer: { x: 485, y: 135, w: 330, h: 86 },
			gears: { x: 410, y: 245, w: 220, h: 118 }
		};

		const shafts = [
			{ x: 310, y: 300, expected: "drive-a" },
			{ x: 397, y: 260, expected: "drive-b" },
			{ x: 480, y: 310, expected: "drive-c" },
			{ x: 566, y: 285, expected: "drive-d" }
		];
		const driveInput = { x: 205, y: 300, r: 54 };
		const driveOutput = { x: 644, y: 300, r: 41 };

		function makeGears() {
			return [
				{ id: "drive-a", r: 51, x: 742, y: 205, homeX: 742, homeY: 205, slot: null, shakeUntil: 0 },
				{ id: "drive-b", r: 45, x: 838, y: 205, homeX: 838, homeY: 205, slot: null, shakeUntil: 0 },
				{ id: "drive-c", r: 52, x: 742, y: 320, homeX: 742, homeY: 320, slot: null, shakeUntil: 0 },
				{ id: "drive-d", r: 38, x: 838, y: 320, homeX: 838, homeY: 320, slot: null, shakeUntil: 0 },
				{ id: "spare-a", r: 42, x: 742, y: 430, homeX: 742, homeY: 430, slot: null, shakeUntil: 0 },
				{ id: "spare-b", r: 30, x: 838, y: 430, homeX: 838, homeY: 430, slot: null, shakeUntil: 0 }
			];
		}

		function getTransmissionState() {
			const placed = shafts.map((_shaft, index) => state.gears.find((gear) => gear.slot === index) || null);
			const nodes = [driveInput].concat(placed, [driveOutput]);
			const links = [];
			const connectedNodes = [true];
			for (let index = 0; index < nodes.length - 1; index += 1) {
				const from = nodes[index];
				const to = nodes[index + 1];
				const ready = Boolean(from && to);
				const axleDistance = ready ? distance(from, to) : 0;
				const gapError = ready ? Math.abs(axleDistance - (from.r + to.r)) : Infinity;
				const meshed = ready && gapError <= 1.8;
				links.push({ from, to, ready, meshed, axleDistance, gapError });
				connectedNodes.push(Boolean(connectedNodes[index] && meshed));
			}
			return {
				nodes,
				links,
				connectedNodes,
				complete: placed.every(Boolean) && links.every((link) => link.meshed)
			};
		}

		const state = {
			version: "2.3.0",
			status: "ready",
			phase: "inspect",
			enabled: true,
			muted: Boolean(config.muted),
			inspected: { speaker: false, wires: false, knob: false, pointer: false, gears: false },
			partFlash: {},
			knobAngle: -.7,
			fixedPointer: .28,
			gears: makeGears(),
			dragGear: null,
			dragOffset: { x: 0, y: 0 },
			gearEngaged: false,
			gearStartAt: 0,
			lastGearProgressAt: 0,
			assistLevel: 0,
			highlightShaftUntil: 0,
			coarse: .28,
			fine: 0,
			targetCoarse: .68,
			targetFine: .035,
			coarseKnobAngle: knobRotationFromNormalized(.28),
			fineKnobAngle: knobRotationFromNormalized(.5),
			dragTune: null,
			dragTuneAngle: null,
			dragStartX: 0,
			dragStartValue: 0,
			quality: 0,
			targetQuality: 0,
			stableFor: 0,
			signalLocked: false,
			fineHintShown: false,
			hover: null,
			pointerId: null,
			hint: "",
			hintTimer: null,
			phaseTimer: null,
			completionSent: false,
			nextDestination: config.nextDestination || null
		};

		let destroyed = false;
		let frame = 0;
		let lastFrame = performance.now();
		let audio = null;
		let textureSeed = 1977;
		const rustSpots = Array.from({ length: 180 }, () => {
			textureSeed = textureSeed * 16807 % 2147483647;
			const x = textureSeed / 2147483647;
			textureSeed = textureSeed * 16807 % 2147483647;
			const y = textureSeed / 2147483647;
			textureSeed = textureSeed * 16807 % 2147483647;
			return { x, y, size: 1 + textureSeed % 3, bright: textureSeed % 5 === 0 };
		});

		function snapshot() {
			return {
				version: state.version,
				status: state.status,
				solved: state.status === "complete",
				phase: state.phase,
				task: phaseTask(state.phase),
				enabled: state.enabled,
				muted: state.muted,
				inspected: Object.assign({}, state.inspected),
				gears: state.gears.map((gear) => ({ id: gear.id, slot: gear.slot })),
				coarseFrequency: state.coarse,
				fineFrequency: state.fine,
				coarseKnobAngle: state.coarseKnobAngle,
				fineKnobAngle: state.fineKnobAngle,
				signalQuality: state.quality,
				signalTargetQuality: state.targetQuality,
				signalLocked: state.signalLocked,
				nextDestination: state.nextDestination
			};
		}

		function emit(type, detail) {
			const message = {
				source: "gear-calibration",
				version: state.version,
				type,
				detail: detail || snapshot()
			};
			if (typeof config.onEvent === "function") config.onEvent(message);
			window.dispatchEvent(new CustomEvent(type.toLowerCase(), { detail: message.detail }));
		}

		function announce(text) {
			live.textContent = text || "";
		}

		function updateHud() {
			shell.dataset.phase = state.phase;
			taskText.textContent = phaseTask(state.phase);
			guideText.textContent = phaseGuide(state.phase);
			taskText.classList.remove("is-changing");
			void taskText.offsetWidth;
			taskText.classList.add("is-changing");
			hintText.hidden = !state.hint;
			hintText.textContent = state.hint;
			hintText.classList.toggle("is-visible", Boolean(state.hint));
		}

		function showHint(text, duration) {
			if (state.hintTimer) window.clearTimeout(state.hintTimer);
			state.hint = text || "";
			updateHud();
			if (text) {
				announce(text);
				state.hintTimer = window.setTimeout(() => {
					state.hint = "";
					state.hintTimer = null;
					updateHud();
				}, duration || 2200);
			}
		}

		function ensureAudio() {
			if (state.muted || audio) return audio;
			try {
				const AudioCtor = window.AudioContext || window.webkitAudioContext;
				if (!AudioCtor) return null;
				const context = new AudioCtor();
				const noiseBuffer = context.createBuffer(1, context.sampleRate * 2, context.sampleRate);
				const data = noiseBuffer.getChannelData(0);
				for (let i = 0; i < data.length; i += 1) data[i] = Math.random() * 2 - 1;
				const noise = context.createBufferSource();
				const noiseFilter = context.createBiquadFilter();
				const noiseGain = context.createGain();
				noise.buffer = noiseBuffer;
				noise.loop = true;
				noiseFilter.type = "bandpass";
				noiseFilter.frequency.value = 1800;
				noiseGain.gain.value = 0;
				noise.connect(noiseFilter).connect(noiseGain).connect(context.destination);
				noise.start();
				const tone = context.createOscillator();
				const toneGain = context.createGain();
				tone.type = "triangle";
				tone.frequency.value = 246.94;
				toneGain.gain.value = 0;
				tone.connect(toneGain).connect(context.destination);
				tone.start();
				audio = { context, noise, noiseGain, tone, toneGain };
				return audio;
			} catch (_error) {
				return null;
			}
		}

		function setSignalAudio(quality, speakerBurst) {
			if (state.muted) return;
			const system = ensureAudio();
			if (!system) return;
			const now = system.context.currentTime;
			const noiseLevel = speakerBurst ? .075 : state.phase === "tune" ? .045 * (1 - quality) : 0;
			const toneLevel = state.phase === "complete" ? .026 : state.phase === "tune" ? .015 * quality : 0;
			system.noiseGain.gain.cancelScheduledValues(now);
			system.noiseGain.gain.setTargetAtTime(noiseLevel, now, .035);
			system.toneGain.gain.setTargetAtTime(toneLevel, now, .05);
			if (speakerBurst) window.setTimeout(() => {
				if (audio) audio.noiseGain.gain.setTargetAtTime(0, audio.context.currentTime, .05);
			}, 260);
		}

		function clickSound(frequency, duration) {
			if (state.muted) return;
			const system = ensureAudio();
			if (!system) return;
			const oscillator = system.context.createOscillator();
			const gain = system.context.createGain();
			oscillator.type = "square";
			oscillator.frequency.value = frequency;
			gain.gain.value = .028;
			gain.gain.exponentialRampToValueAtTime(.0001, system.context.currentTime + duration);
			oscillator.connect(gain).connect(system.context.destination);
			oscillator.start();
			oscillator.stop(system.context.currentTime + duration);
		}

		function start() {
			if (!state.enabled || state.status !== "ready") return false;
			state.status = "playing";
			announce("检查收音机故障");
			emit("GEAR_CALIBRATION_START");
			updateHud();
			return true;
		}

		function setPhase(phase, silent) {
			if (!["inspect", "gears", "tune", "complete"].includes(phase)) return false;
			if (state.phaseTimer) window.clearTimeout(state.phaseTimer);
			state.phase = phase;
			state.hover = null;
			state.dragGear = null;
			state.dragTune = null;
			state.dragTuneAngle = null;
			if (phase === "gears") {
				state.lastGearProgressAt = performance.now();
				state.assistLevel = 0;
			} else if (phase === "tune") {
				state.stableFor = 0;
				state.signalLocked = false;
				updateTuningAudio();
				setSignalAudio(state.quality, false);
			} else if (phase === "complete") {
				completeRepair();
			}
			updateHud();
			if (!silent) {
				announce(phaseTask(phase));
				emit("RADIO_REPAIR_PHASE", snapshot());
			}
			return true;
		}

		function completeRepair() {
			if (state.status === "settling" || state.status === "complete") return;
			state.status = "settling";
			state.signalLocked = true;
			state.quality = 1;
			state.targetQuality = 1;
			setSignalAudio(1, false);
			showHint("信号已稳定", 1400);
			clickSound(784, .22);
			updateHud();
			state.phaseTimer = window.setTimeout(() => {
				if (destroyed) return;
				state.status = "complete";
				state.phase = "complete";
				state.hint = "";
				setSignalAudio(1, false);
				updateHud();
				announce("维修完成");
				state.phaseTimer = window.setTimeout(() => {
					if (destroyed || state.completionSent) return;
					state.completionSent = true;
					const detail = snapshot();
					emit("GEAR_CALIBRATION_COMPLETE", detail);
					window.dispatchEvent(new CustomEvent("radioRepairComplete", { detail }));
				}, 900);
			}, 650);
		}

		function reset(resetOptions) {
			const shouldStart = Boolean(resetOptions && resetOptions.start);
			if (state.hintTimer) window.clearTimeout(state.hintTimer);
			if (state.phaseTimer) window.clearTimeout(state.phaseTimer);
			Object.assign(state, {
				status: shouldStart ? "playing" : "ready",
				phase: "inspect",
				inspected: { speaker: false, wires: false, knob: false, pointer: false, gears: false },
				partFlash: {},
				knobAngle: -.7,
				gears: makeGears(),
				dragGear: null,
				gearEngaged: false,
				assistLevel: 0,
				coarse: .28,
				fine: 0,
				coarseKnobAngle: knobRotationFromNormalized(.28),
				fineKnobAngle: knobRotationFromNormalized(.5),
				dragTune: null,
				dragTuneAngle: null,
				quality: 0,
				targetQuality: 0,
				stableFor: 0,
				signalLocked: false,
				fineHintShown: false,
				hint: "",
				completionSent: false
			});
			setSignalAudio(0, false);
			updateHud();
			emit("GEAR_CALIBRATION_RESET");
			return true;
		}

		function canvasPoint(event) {
			const rect = canvas.getBoundingClientRect();
			return {
				x: (event.clientX - rect.left) / rect.width * WIDTH,
				y: (event.clientY - rect.top) / rect.height * HEIGHT
			};
		}

		function inspectHit(point) {
			if (pointInCircle(point, inspectParts.speaker)) return "speaker";
			if (pointInRect(point, inspectParts.wires)) return "wires";
			if (pointInCircle(point, inspectParts.knob)) return "knob";
			if (pointInRect(point, inspectParts.pointer)) return "pointer";
			if (pointInRect(point, inspectParts.gears)) return "gears";
			return null;
		}

		function handleInspectDown(point) {
			const part = inspectHit(point);
			state.hover = part;
			if (!part) return;
			state.inspected[part] = true;
			state.partFlash[part] = performance.now() + 420;
			if (part === "speaker") {
				setSignalAudio(0, true);
				showHint("扬声器正常", 1500);
			} else if (part === "wires") {
				clickSound(360, .06);
				showHint("线路连接正常", 1500);
			} else if (part === "knob") {
				state.dragTune = "inspectKnob";
				state.dragStartX = point.x;
				state.dragStartValue = state.knobAngle;
				clickSound(310, .04);
				showHint("主旋钮正常", 1500);
			} else if (part === "pointer") {
				clickSound(120, .08);
				showHint("调频指针无响应", 1700);
			} else if (part === "gears") {
				if (state.inspected.knob && state.inspected.pointer) {
					showHint("传动结构异常", 1100);
					state.phaseTimer = window.setTimeout(() => setPhase("gears"), 520);
				} else showHint("先检查旋钮与调频指针", 1600);
			}
			emit("RADIO_REPAIR_INSPECT", { part, state: snapshot() });
		}

		function availableGearAt(point) {
			return state.gears.slice().reverse().find((gear) => distance(point, gear) <= gear.r + 10) || null;
		}

		function handleGearDown(point) {
			const gear = availableGearAt(point);
			if (!gear) return;
			state.dragGear = gear.id;
			state.dragOffset.x = point.x - gear.x;
			state.dragOffset.y = point.y - gear.y;
			if (gear.slot !== null) gear.slot = null;
			clickSound(210, .04);
		}

		function releaseGear(now) {
			const gear = state.gears.find((item) => item.id === state.dragGear);
			state.dragGear = null;
			if (!gear) return;
			let nearest = null;
			let nearestDistance = Infinity;
			shafts.forEach((shaft, index) => {
				const gap = distance(gear, shaft);
				if (gap < nearestDistance) {
					nearestDistance = gap;
					nearest = index;
				}
			});
			if (nearest === null || nearestDistance > 68 || state.gears.some((item) => item !== gear && item.slot === nearest)) {
				gear.x = gear.homeX;
				gear.y = gear.homeY;
				gear.shakeUntil = now + 260;
				clickSound(105, .12);
				return;
			}
			gear.slot = nearest;
			gear.x = shafts[nearest].x;
			gear.y = shafts[nearest].y;
			state.lastGearProgressAt = now;
			clickSound(520, .07);
			const transmission = getTransmissionState();
			const neighboringLinks = [transmission.links[nearest], transmission.links[nearest + 1]].filter(Boolean);
			if (neighboringLinks.some((link) => link.ready && !link.meshed)) {
				gear.shakeUntil = now + 320;
				showHint("齿轮间距不匹配", 1500);
				clickSound(105, .1);
			}
			const allPlaced = shafts.every((_shaft, index) => state.gears.some((item) => item.slot === index));
			if (!allPlaced) return;
			const correct = transmission.complete;
			if (!correct) {
				showHint("当前传动方向不正确", 1800);
				state.gears.forEach((item) => item.shakeUntil = now + 520);
				clickSound(82, .2);
				state.phaseTimer = window.setTimeout(() => {
					state.gears.filter((item) => shafts[item.slot] && shafts[item.slot].expected !== item.id).forEach((item) => {
						item.slot = null;
						item.x = item.homeX;
						item.y = item.homeY;
					});
				}, 620);
				return;
			}
			state.gearEngaged = true;
			state.gearStartAt = now;
			clickSound(640, .12);
			state.phaseTimer = window.setTimeout(() => setPhase("tune"), 1150);
		}

		function tuneControlAt(point) {
			if (pointInCircle(point, { x: TUNING_CONTROLS.coarse.x, y: TUNING_CONTROLS.coarse.y, r: TUNING_CONTROLS.coarse.hitRadius })) return "coarse";
			if (pointInCircle(point, { x: TUNING_CONTROLS.fine.x, y: TUNING_CONTROLS.fine.y, r: TUNING_CONTROLS.fine.hitRadius })) return "fine";
			return null;
		}

		function tuneAngleAt(control, point) {
			const spec = TUNING_CONTROLS[control];
			if (!spec || Math.hypot(point.x - spec.x, point.y - spec.y) < 4) return null;
			return normalizeAngle(Math.atan2(point.y - spec.y, point.x - spec.x) + Math.PI / 2);
		}

		function updateTuneFromPoint(control, point) {
			const spec = TUNING_CONTROLS[control];
			const nextAngle = tuneAngleAt(control, point);
			if (!spec || nextAngle === null) return;
			const previousAngle = state.dragTuneAngle === null ? state[spec.angleKey] : state.dragTuneAngle;
			state[spec.angleKey] = nextAngle;
			state.dragTuneAngle = nextAngle;
			state[control] = clamp(
				state[control] + shortestAngleDelta(nextAngle, previousAngle) * spec.valuePerRadian,
				spec.min,
				spec.max
			);
			updateTuningAudio();
		}

		function handleTuneDown(point) {
			if (state.signalLocked) return;
			const control = tuneControlAt(point);
			if (!control) return;
			state.dragTune = control;
			state.dragTuneAngle = null;
			updateTuneFromPoint(control, point);
			clickSound(control === "coarse" ? 260 : 390, .035);
		}

		function updateTuningAudio() {
			if (state.signalLocked) return;
			const coarseError = Math.abs(state.coarse - state.targetCoarse);
			const fineError = Math.abs(state.fine - state.targetFine);
			state.targetQuality = clamp(
				1 - coarseError * TUNING_QUALITY.coarseWeight - fineError * TUNING_QUALITY.fineWeight,
				0,
				1
			);
			if (coarseError < .045 && fineError > .018 && !state.fineHintShown) {
				state.fineHintShown = true;
				showHint("使用微调降低杂音", 2000);
			}
		}

		function lockSignal() {
			if (state.signalLocked || state.phase !== "tune") return;
			state.signalLocked = true;
			state.coarse = state.targetCoarse;
			state.fine = state.targetFine;
			state.quality = 1;
			state.targetQuality = 1;
			state.dragTune = null;
			state.dragTuneAngle = null;
			state.hover = null;
			setSignalAudio(1, false);
			showHint("信号已锁定", 1400);
			clickSound(720, .14);
			state.phaseTimer = window.setTimeout(() => completeRepair(), 700);
		}

		function onPointerDown(event) {
			if (!state.enabled || event.button !== undefined && event.button !== 0) return;
			ensureAudio();
			if (state.status === "ready") start();
			if (state.status !== "playing") return;
			const point = canvasPoint(event);
			state.pointerId = event.pointerId;
			if (state.phase === "inspect") handleInspectDown(point);
			else if (state.phase === "gears") handleGearDown(point);
			else if (state.phase === "tune") handleTuneDown(point);
			canvas.setPointerCapture && canvas.setPointerCapture(event.pointerId);
			event.preventDefault();
		}

		function onPointerMove(event) {
			const point = canvasPoint(event);
			if (state.phase === "inspect") state.hover = inspectHit(point);
			else if (state.phase === "gears") {
				state.hover = availableGearAt(point) ? "gear" : null;
				if (state.dragGear) {
					const gear = state.gears.find((item) => item.id === state.dragGear);
					gear.x = point.x - state.dragOffset.x;
					gear.y = point.y - state.dragOffset.y;
				}
			} else if (state.phase === "tune") {
				state.hover = tuneControlAt(point);
				if (state.dragTune === "coarse" || state.dragTune === "fine") updateTuneFromPoint(state.dragTune, point);
			}
			if (state.dragTune === "inspectKnob") state.knobAngle = clamp(state.dragStartValue + (point.x - state.dragStartX) / 130, -2.2, 2.2);
			if (state.pointerId === event.pointerId) event.preventDefault();
		}

		function onPointerUp(event) {
			if (state.pointerId !== event.pointerId) return;
			if (state.phase === "gears" && state.dragGear) releaseGear(performance.now());
			state.dragTune = null;
			state.dragTuneAngle = null;
			state.pointerId = null;
			canvas.releasePointerCapture && canvas.releasePointerCapture(event.pointerId);
			event.preventDefault();
		}

		function drawMetalTexture(x, y, w, h, strength) {
			ctx.save();
			ctx.globalAlpha = strength === undefined ? .35 : strength;
			rustSpots.forEach((spot) => {
				ctx.fillStyle = spot.bright ? "#9b5425" : "#060402";
				ctx.fillRect(Math.round(x + spot.x * w), Math.round(y + spot.y * h), spot.size, spot.size);
			});
			ctx.restore();
		}

		function drawScrew(x, y, radius) {
			ctx.fillStyle = "#080503";
			ctx.beginPath();
			ctx.arc(x + 1, y + 2, radius + 2, 0, TAU);
			ctx.fill();
			ctx.fillStyle = "#6f4423";
			ctx.beginPath();
			ctx.arc(x, y, radius, 0, TAU);
			ctx.fill();
			ctx.strokeStyle = "#bd7738";
			ctx.lineWidth = 1;
			ctx.beginPath();
			ctx.moveTo(x - radius * .55, y + radius * .3);
			ctx.lineTo(x + radius * .55, y - radius * .3);
			ctx.stroke();
		}

		function drawPixelPanel(x, y, w, h) {
			ctx.fillStyle = "#050302";
			ctx.fillRect(x - 7, y - 7, w + 14, h + 14);
			ctx.fillStyle = "#3b2414";
			ctx.fillRect(x - 3, y - 3, w + 6, h + 6);
			ctx.fillStyle = COLORS.panel;
			ctx.fillRect(x, y, w, h);
			drawMetalTexture(x + 3, y + 3, w - 6, h - 6, .32);
			ctx.strokeStyle = "#b16c31";
			ctx.lineWidth = 2;
			ctx.strokeRect(x + 1, y + 1, w - 2, h - 2);
			ctx.strokeStyle = "#4b2d19";
			ctx.strokeRect(x + 7, y + 7, w - 14, h - 14);
			drawScrew(x + 12, y + 12, 5);
			drawScrew(x + w - 12, y + 12, 5);
			drawScrew(x + 12, y + h - 12, 5);
			drawScrew(x + w - 12, y + h - 12, 5);
		}

		function drawStatusTag(x, y, text, fault) {
			ctx.font = "11px PixelCJK, monospace";
			ctx.textAlign = "center";
			const width = Math.max(54, ctx.measureText(text).width + 18);
			ctx.fillStyle = "rgba(8, 5, 3, .9)";
			ctx.fillRect(x - width / 2, y - 12, width, 22);
			ctx.strokeStyle = fault ? "#a95d43" : "#778268";
			ctx.strokeRect(x - width / 2 + .5, y - 11.5, width - 1, 21);
			ctx.fillStyle = fault ? "#d49375" : "#bac3a2";
			ctx.fillText(text, x, y + 4);
		}

		function drawGear(x, y, radius, angle, active, shake) {
			ctx.save();
			ctx.translate(x + (shake ? Math.sin(performance.now() * .11) * 4 : 0), y);
			ctx.rotate(angle);
			ctx.fillStyle = active ? "#9d642f" : "#63401f";
			const teeth = radius > 45 ? 16 : radius > 34 ? 14 : 12;
			for (let tooth = 0; tooth < teeth; tooth += 1) {
				ctx.save();
				ctx.rotate(tooth / teeth * TAU);
				ctx.fillRect(radius - 4, -7, 12, 14);
				ctx.restore();
			}
			ctx.beginPath();
			ctx.arc(0, 0, radius, 0, TAU);
			ctx.fill();
			ctx.strokeStyle = active ? "#d09550" : "#9b6333";
			ctx.lineWidth = 3;
			ctx.stroke();
			ctx.strokeStyle = "#3d2615";
			ctx.lineWidth = Math.max(4, radius * .12);
			ctx.beginPath();
			ctx.arc(0, 0, radius * .72, 0, TAU);
			ctx.stroke();
			ctx.fillStyle = COLORS.ink;
			ctx.beginPath();
			ctx.arc(0, 0, Math.max(8, radius * .28), 0, TAU);
			ctx.fill();
			ctx.strokeStyle = "#c17b3b";
			ctx.lineWidth = 4;
			for (let spoke = 0; spoke < 5; spoke += 1) {
				const spokeAngle = spoke / 5 * TAU;
				ctx.beginPath();
				ctx.moveTo(Math.cos(spokeAngle) * radius * .34, Math.sin(spokeAngle) * radius * .34);
				ctx.lineTo(Math.cos(spokeAngle) * radius * .78, Math.sin(spokeAngle) * radius * .78);
				ctx.stroke();
			}
			ctx.fillStyle = "rgba(233, 170, 87, .34)";
			ctx.fillRect(-radius * .48, -radius * .62, radius * .35, 2);
			ctx.restore();
		}

		function drawInspect(now) {
			drawPixelPanel(70, 52, 860, 456);
			ctx.fillStyle = "#21150d";
			ctx.fillRect(92, 74, 816, 412);
			drawMetalTexture(92, 74, 816, 412, .46);

			ctx.fillStyle = "#080503";
			ctx.beginPath();
			ctx.arc(230, 290, 112, 0, TAU);
			ctx.fill();
			ctx.strokeStyle = state.hover === "speaker" || state.partFlash.speaker > now ? "#d08a48" : "#784824";
			ctx.lineWidth = 8;
			ctx.stroke();
			ctx.strokeStyle = "#302016";
			ctx.lineWidth = 3;
			ctx.beginPath();
			ctx.arc(230, 290, 100, 0, TAU);
			ctx.stroke();
			for (let row = -6; row <= 6; row += 1) for (let col = -6; col <= 6; col += 1) {
				const hx = 230 + col * 15 + (row % 2 ? 7 : 0);
				const hy = 290 + row * 13;
				if (Math.hypot(hx - 230, hy - 290) < 85) {
					ctx.fillStyle = "#020201";
					ctx.beginPath();
					ctx.arc(hx, hy, 4.5, 0, TAU);
					ctx.fill();
				}
			}
			drawScrew(163, 220, 6); drawScrew(297, 220, 6);
			drawScrew(163, 360, 6); drawScrew(297, 360, 6);

			drawPixelPanel(458, 104, 398, 130);
			ctx.fillStyle = "#070503";
			ctx.fillRect(474, 120, 366, 98);
			ctx.fillStyle = "#cf8435";
			ctx.font = "15px PixelCJK, monospace";
			ctx.textAlign = "left";
			ctx.fillText("FM", 490, 145);
			ctx.fillText("AM", 490, 198);
			ctx.font = "12px PixelCJK, monospace";
			[88, 92, 96, 100, 104, 108].forEach((value, index) => {
				const x = 548 + index * 53;
				ctx.textAlign = "center";
				ctx.fillText(String(value), x, 144);
				ctx.fillRect(x, 153, 2, 22);
			});
			ctx.strokeStyle = "#75471f";
			ctx.lineWidth = 3;
			ctx.beginPath();
			ctx.moveTo(535, 178);
			ctx.lineTo(820, 178);
			ctx.stroke();
			const needleX = 535 + state.fixedPointer * 285;
			ctx.fillStyle = "#de8b35";
			ctx.fillRect(needleX - 2, 152, 5, 51);
			ctx.strokeStyle = state.hover === "pointer" || state.partFlash.pointer > now ? "#e0a35f" : "#4b2e19";
			ctx.lineWidth = 2;
			ctx.strokeRect(478, 124, 358, 90);

			drawPixelPanel(400, 254, 242, 126);
			ctx.fillStyle = "#070503";
			ctx.fillRect(416, 270, 210, 94);
			const focusGear = state.hover === "gears" || state.partFlash.gears > now;
			drawGear(476, 317, 38, now * .0001, focusGear, false);
			drawGear(556, 317, 28, -now * .00014, focusGear, false);

			ctx.strokeStyle = state.partFlash.wires > now ? "#a7a77a" : "#6d4b2c";
			ctx.lineWidth = state.partFlash.wires > now ? 5 : 3;
			[[356, 414, 420, 390, 478, 430, 554, 402], [356, 442, 430, 458, 492, 428, 568, 448]].forEach((wire) => {
				ctx.beginPath();
				ctx.moveTo(wire[0], wire[1]);
				ctx.bezierCurveTo(wire[2], wire[3], wire[4], wire[5], wire[6], wire[7]);
				ctx.stroke();
			});

			drawKnob(765, 370, 62, (state.knobAngle + 2.2) / 4.4, "主旋钮", state.hover === "knob");

			if (state.inspected.speaker) drawStatusTag(230, 415, "正常", false);
			if (state.inspected.wires) drawStatusTag(465, 463, "线路正常", false);
			if (state.inspected.knob) drawStatusTag(765, 463, "可转动", false);
			if (state.inspected.pointer) drawStatusTag(804, 248, "无响应", true);
			if (state.inspected.gears) drawStatusTag(520, 392, "传动异常", true);
		}

		function drawGears(now) {
			drawPixelPanel(92, 62, 816, 438);
			ctx.fillStyle = "#11100c";
			ctx.fillRect(118, 88, 560, 386);
			ctx.fillStyle = "#211e17";
			ctx.fillRect(700, 88, 180, 386);
			ctx.fillStyle = COLORS.dim;
			ctx.font = "16px PixelCJK, monospace";
			ctx.fillText("备用齿轮", 744, 126);

			const spin = state.gearEngaged ? (now - state.gearStartAt) * .0024 : now * .00015;
			drawGear(225, 300, 62, spin, state.gearEngaged, false);
			drawGear(600, 300, 44, spin, state.gearEngaged, false);
			shafts.forEach((shaft, index) => {
				const highlighted = state.highlightShaftUntil > now && !state.gears.some((gear) => gear.slot === index);
				ctx.fillStyle = highlighted ? "#aaa17c" : "#39362c";
				ctx.beginPath();
				ctx.arc(shaft.x, shaft.y, 9, 0, TAU);
				ctx.fill();
				ctx.strokeStyle = highlighted ? "#c1b692" : "#5e5948";
				ctx.strokeRect(shaft.x - shaft.r - 8, shaft.y - shaft.r - 8, (shaft.r + 8) * 2, (shaft.r + 8) * 2);
			});
			state.gears.forEach((gear) => {
				const angle = gear.slot === null ? now * .00008 : spin * (gear.slot % 2 ? -1 : 1);
				drawGear(gear.x, gear.y, gear.r, angle, gear.slot !== null, gear.shakeUntil > now);
			});
		}

		function drawGearsV2(now) {
			drawPixelPanel(68, 52, 864, 456);
			ctx.font = "bold 18px PixelCJK, monospace";
			ctx.textAlign = "center";
			ctx.lineJoin = "round";
			ctx.lineWidth = 4;
			ctx.strokeStyle = "rgba(24, 10, 3, .96)";
			ctx.strokeText("提示：显示数字是两个齿轮的半径之和", 500, 72);
			ctx.fillStyle = "#ffd36f";
			ctx.fillText("提示：显示数字是两个齿轮的半径之和", 500, 72);
			ctx.fillStyle = "#0a0704";
			ctx.fillRect(92, 78, 580, 404);
			drawMetalTexture(92, 78, 580, 404, .22);
			ctx.fillStyle = "#21150d";
			ctx.fillRect(688, 78, 220, 404);
			drawMetalTexture(688, 78, 220, 404, .42);
			ctx.strokeStyle = "#6f421f";
			ctx.lineWidth = 2;
			ctx.strokeRect(696, 86, 204, 388);
			ctx.fillStyle = COLORS.light;
			ctx.font = "15px PixelCJK, monospace";
			ctx.textAlign = "center";
			ctx.fillText("备选齿轮", 798, 112);
			ctx.fillStyle = "#8b6747";
			ctx.font = "10px PixelCJK, monospace";
			ctx.fillText("数字为齿数 · 绿线会传动", 798, 132);

			const transmission = getTransmissionState();
			const axleNodes = [driveInput].concat(shafts, [driveOutput]);
			transmission.links.forEach((link, index) => {
				const from = axleNodes[index];
				const to = axleNodes[index + 1];
				ctx.strokeStyle = !link.ready ? "#51331c" : link.meshed ? "#778568" : "#9f4939";
				ctx.lineWidth = link.ready ? 4 : 2;
				ctx.beginPath();
				ctx.moveTo(from.x, from.y);
				ctx.lineTo(to.x, to.y);
				ctx.stroke();
			});

			const spin = now * .0022;
			drawGear(driveInput.x, driveInput.y, driveInput.r, spin, true, false);
			const outputActive = transmission.connectedNodes[transmission.connectedNodes.length - 1];
			drawGear(driveOutput.x, driveOutput.y, driveOutput.r, -spin, outputActive, false);
			ctx.fillStyle = "#a1764f";
			ctx.font = "10px PixelCJK, monospace";
			ctx.fillText("动力", 205, 382);
			ctx.fillText("调谐轴", 644, 365);
			shafts.forEach((shaft, index) => {
				const occupied = state.gears.some((gear) => gear.slot === index);
				const highlighted = state.highlightShaftUntil > now && !occupied;
				ctx.fillStyle = highlighted ? "#e1a45c" : "#4c3422";
				ctx.beginPath();
				ctx.arc(shaft.x, shaft.y, highlighted ? 13 : 9, 0, TAU);
				ctx.fill();
				ctx.strokeStyle = highlighted ? "#f0bd72" : "#986139";
				ctx.lineWidth = 2;
				ctx.beginPath();
				ctx.arc(shaft.x, shaft.y, highlighted ? 18 : 13, 0, TAU);
				ctx.stroke();
			});
			state.gears.forEach((gear) => {
				const active = gear.slot !== null && transmission.connectedNodes[gear.slot + 1];
				const angle = active ? spin * (gear.slot % 2 ? 1 : -1) : 0;
				drawGear(gear.x, gear.y, gear.r, angle, active, gear.shakeUntil > now);
			});
			ctx.fillStyle = "#efd09a";
			ctx.font = "9px PixelCJK, monospace";
			ctx.textAlign = "center";
			ctx.font = "13px PixelCJK, monospace";
			ctx.fillText(String(driveInput.r), driveInput.x, driveInput.y + 5);
			ctx.fillText(String(driveOutput.r), driveOutput.x, driveOutput.y + 5);
			state.gears.forEach((gear) => ctx.fillText(String(gear.r), gear.x, gear.y + 5));
			transmission.links.forEach((link, index) => {
				const from = axleNodes[index];
				const to = axleNodes[index + 1];
				const fromRadius = transmission.nodes[index] ? transmission.nodes[index].r : 9;
				const toRadius = transmission.nodes[index + 1] ? transmission.nodes[index + 1].r : 9;
				const label = String(Math.round(distance(from, to))) + (link.ready ? link.meshed ? " ✓" : " ×" : "");
				const x = (from.x + to.x) / 2;
				const y = Math.min(from.y - fromRadius, to.y - toRadius) - 13;
				ctx.font = "600 13px PixelCJK, monospace";
				ctx.fillStyle = !link.ready ? "#a77b4e" : link.meshed ? "#c0cca5" : "#dfa084";
				ctx.textAlign = "center";
				ctx.fillText(label, x, y + 4);
			});
		}

		function drawKnob(x, y, radius, normalized, label, active, pointerAngle) {
			ctx.save();
			ctx.translate(x, y);
			ctx.fillStyle = "#070503";
			ctx.beginPath();
			ctx.arc(0, 2, radius + 10, 0, TAU);
			ctx.fill();
			ctx.strokeStyle = active ? "#d4944e" : "#714520";
			ctx.lineWidth = 6;
			ctx.beginPath();
			ctx.arc(0, 0, radius + 5, 0, TAU);
			ctx.stroke();
			ctx.strokeStyle = "#9a6231";
			ctx.lineWidth = 2;
			for (let notch = 0; notch < 20; notch += 1) {
				const a = notch / 20 * TAU;
				ctx.beginPath();
				ctx.moveTo(Math.cos(a) * (radius + 1), Math.sin(a) * (radius + 1));
				ctx.lineTo(Math.cos(a) * (radius + 9), Math.sin(a) * (radius + 9));
				ctx.stroke();
			}
			ctx.fillStyle = active ? "#704623" : "#3c291b";
			ctx.beginPath();
			ctx.arc(0, 0, radius, 0, TAU);
			ctx.fill();
			ctx.save();
			ctx.beginPath();
			ctx.arc(0, 0, radius - 1, 0, TAU);
			ctx.clip();
			drawMetalTexture(-radius, -radius, radius * 2, radius * 2, .2);
			ctx.restore();
			ctx.strokeStyle = active ? "#e0a45e" : "#976039";
			ctx.lineWidth = 4;
			ctx.stroke();
			ctx.rotate(Number.isFinite(pointerAngle) ? pointerAngle : knobRotationFromNormalized(normalized));
			ctx.fillStyle = "#e1a45a";
			ctx.fillRect(-3, -radius + 9, 6, Math.max(14, radius * .35));
			ctx.restore();
			ctx.fillStyle = "#b98a5b";
			ctx.font = "14px PixelCJK, monospace";
			ctx.textAlign = "center";
			ctx.fillText(label, x, y + radius + 28);
		}

		function drawTune(now) {
			drawPixelPanel(105, 64, 790, 432);
			ctx.fillStyle = "#0c0d0a";
			ctx.fillRect(190, 108, 620, 168);
			ctx.strokeStyle = "#4a5142";
			ctx.lineWidth = 1;
			for (let x = 210; x <= 790; x += 29) {
				ctx.beginPath();
				ctx.moveTo(x, 118);
				ctx.lineTo(x, 264);
				ctx.stroke();
			}
			ctx.strokeStyle = state.quality > .86 ? "#89977c" : "#8e7147";
			ctx.lineWidth = 3;
			ctx.beginPath();
			for (let x = 0; x <= 580; x += 5) {
				const noise = (1 - state.quality) * (Math.sin(x * 1.73 + now * .017) + Math.sin(x * .47 + now * .009)) * 19;
				const signal = Math.sin(x * .075 + now * .004) * (7 + state.quality * 9);
				const y = 192 + signal + noise;
				x === 0 ? ctx.moveTo(210, y) : ctx.lineTo(210 + x, y);
			}
			ctx.stroke();
			ctx.fillStyle = "#b2894b";
			ctx.fillRect(208 + state.coarse * 584, 116, 4, 148);

			drawKnob(330, 395, 72, state.coarse, "主调频", state.dragTune === "coarse" || state.hover === "coarse", state.coarseKnobAngle);
			drawKnob(720, 405, 48, (state.fine + .12) / .24, "微调", state.dragTune === "fine" || state.hover === "fine", state.fineKnobAngle);
			ctx.fillStyle = "#161712";
			ctx.fillRect(470, 348, 130, 78);
			ctx.strokeStyle = "#565d4d";
			ctx.strokeRect(471, 349, 128, 76);
			ctx.fillStyle = state.quality > .92 ? "#879a79" : state.quality > .55 ? "#8e7b4e" : "#654b3f";
			const bars = Math.round(state.quality * 8);
			for (let i = 0; i < 8; i += 1) ctx.fillRect(484 + i * 13, 400 - i * 5, 7, i < bars ? 14 + i * 5 : 3);

			const driveAngle = now * .0015;
			drawGear(816, 336, 19, driveAngle, true, false);
			drawGear(849, 336, 14, -driveAngle * 1.35, true, false);
			drawGear(874, 336, 11, driveAngle * 1.7, true, false);
		}

		function drawTuneV2(now) {
			drawPixelPanel(70, 52, 860, 456);
			ctx.fillStyle = "#20140c";
			ctx.fillRect(92, 74, 816, 412);
			drawMetalTexture(92, 74, 816, 412, .45);

			drawPixelPanel(166, 92, 680, 142);
			ctx.fillStyle = "#060402";
			ctx.fillRect(183, 109, 646, 108);
			ctx.fillStyle = "#d18a3c";
			ctx.textAlign = "left";
			ctx.font = "16px PixelCJK, monospace";
			ctx.fillText("FM", 201, 139);
			ctx.font = "12px PixelCJK, monospace";
			const fmMarks = [88, 92, 96, 100, 104, 108];
			fmMarks.forEach((value, index) => {
				const x = 278 + index * 97;
				ctx.textAlign = "center";
				ctx.fillText(String(value), x, 137);
				ctx.fillRect(x, 147, 2, 22);
			});
			ctx.strokeStyle = "#75471f";
			ctx.lineWidth = 4;
			ctx.beginPath();
			ctx.moveTo(262, 181);
			ctx.lineTo(788, 181);
			ctx.stroke();
			for (let i = 0; i <= 20; i += 1) {
				const x = 264 + i * 26;
				ctx.fillStyle = i % 4 === 0 ? "#b77a3b" : "#66401f";
				ctx.fillRect(x, 177, 2, i % 4 === 0 ? 14 : 8);
			}
			const dialPosition = clamp(state.coarse + state.fine * .45, 0, 1);
			const needleX = 264 + dialPosition * 520;
			ctx.fillStyle = "#e8993e";
			ctx.fillRect(needleX - 3, 144, 6, 62);

			drawKnob(245, 367, 67, state.coarse, "主频率", state.dragTune === "coarse" || state.hover === "coarse", state.coarseKnobAngle);
			drawKnob(830, 395, 48, (state.fine + .12) / .24, "微调", state.dragTune === "fine" || state.hover === "fine", state.fineKnobAngle);

			drawPixelPanel(390, 286, 252, 150);
			ctx.fillStyle = "#080603";
			ctx.fillRect(408, 305, 216, 112);
			ctx.fillStyle = "#c28a4d";
			ctx.font = "12px PixelCJK, monospace";
			ctx.textAlign = "left";
			ctx.fillText("信号强度", 423, 329);
			const lockedSignal = state.signalLocked || state.status === "settling" || state.status === "complete";
			const bars = lockedSignal ? 10 : Math.round(state.quality * 10);
			for (let i = 0; i < 10; i += 1) {
				const barHeight = 18 + i * 4;
				const x = 423 + i * 18;
				const y = 397 - barHeight;
				ctx.fillStyle = i < bars ? (lockedSignal ? "#a8b48a" : "#ce8438") : "#30251a";
				ctx.fillRect(x, y, 11, barHeight);
				ctx.strokeStyle = "#634124";
				ctx.strokeRect(x + .5, y + .5, 10, barHeight - 1);
			}
			ctx.fillStyle = lockedSignal ? "#b8c49a" : "#8c6540";
			ctx.font = "10px PixelCJK, monospace";
			ctx.textAlign = "center";
			ctx.fillText(lockedSignal ? "信号已锁定" : "继续调整", 516, 412);

			drawPixelPanel(650, 250, 140, 100);
			ctx.fillStyle = "#070503";
			ctx.fillRect(666, 267, 108, 66);
			ctx.strokeStyle = "rgba(112, 78, 45, .45)";
			ctx.lineWidth = 1;
			for (let grid = 0; grid <= 4; grid += 1) {
				ctx.beginPath();
				ctx.moveTo(666 + grid * 27, 267);
				ctx.lineTo(666 + grid * 27, 333);
				ctx.stroke();
				ctx.beginPath();
				ctx.moveTo(666, 267 + grid * 16.5);
				ctx.lineTo(774, 267 + grid * 16.5);
				ctx.stroke();
			}
			ctx.strokeStyle = state.quality > .86 ? "#a8b48a" : "#b67536";
			ctx.lineWidth = 3;
			ctx.beginPath();
			for (let x = 0; x <= 94; x += 3) {
				const noise = (1 - state.quality) * Math.sin(x * 1.43 + now * .016) * 15;
				const signal = Math.sin(x * .16 + now * .004) * (5 + state.quality * 7);
				const y = 300 + signal + noise;
				x === 0 ? ctx.moveTo(673, y) : ctx.lineTo(673 + x, y);
			}
			ctx.stroke();
			ctx.fillStyle = "#9d7249";
			ctx.font = "9px PixelCJK, monospace";
			ctx.textAlign = "center";
			ctx.fillText("波形", 720, 345);

			const driveAngle = now * .0015;
			drawGear(690, 447, 19, driveAngle, true, false);
			drawGear(723, 447, 14, -driveAngle * 1.35, true, false);
			drawGear(748, 447, 11, driveAngle * 1.7, true, false);
		}

		function render(now) {
			ctx.imageSmoothingEnabled = false;
			ctx.clearRect(0, 0, WIDTH, HEIGHT);
			ctx.fillStyle = "#050302";
			ctx.fillRect(0, 0, WIDTH, HEIGHT);
			for (let y = 0; y < HEIGHT; y += 24) {
				ctx.fillStyle = y % 48 ? "#100a06" : "#160e08";
				ctx.fillRect(0, y, WIDTH, 21);
			}
			drawPixelPanel(24, 18, 952, 522);
			ctx.fillStyle = "#0c0805";
			ctx.fillRect(45, 40, 910, 478);
			drawMetalTexture(45, 40, 910, 478, .2);
			if (state.phase === "inspect") drawInspect(now);
			else if (state.phase === "gears") drawGearsV2(now);
			else drawTuneV2(now);
			ctx.textAlign = "left";
			ctx.fillStyle = "rgba(196, 126, 59, .45)";
			ctx.font = "10px PixelCJK, monospace";
			ctx.fillText("RED RADIO / SERVICE BENCH 07", 18, HEIGHT - 16);
		}

		function tick(now) {
			if (destroyed) return;
			const dt = Math.min(.05, Math.max(0, (now - lastFrame) / 1000));
			lastFrame = now;
			if (state.status === "playing" && state.phase === "gears" && !state.gearEngaged) {
				const idle = now - state.lastGearProgressAt;
				if (idle > 8000 && state.assistLevel === 0) {
					state.assistLevel = 1;
					showHint("使齿轮保持连续咬合", 2000);
				} else if (idle > 16000 && state.assistLevel === 1) {
					state.assistLevel = 2;
					state.highlightShaftUntil = now + 1300;
				}
			}
			if (state.status === "playing" && state.phase === "tune" && !state.signalLocked) {
				const qualityDelta = state.targetQuality - state.quality;
				if (Math.abs(qualityDelta) > .0005) {
					state.quality += qualityDelta * (1 - Math.exp(-TUNING_QUALITY.responsePerSecond * dt));
					setSignalAudio(state.quality, false);
				} else state.quality = state.targetQuality;
				const coarseError = Math.abs(state.coarse - state.targetCoarse);
				const fineError = Math.abs(state.fine - state.targetFine);
				if (state.quality >= .95 && coarseError < .035 && fineError < .018) state.stableFor += dt;
				else state.stableFor = Math.max(0, state.stableFor - dt * 1.5);
				if (state.stableFor >= .35) lockSignal();
			}
			render(now);
			frame = window.requestAnimationFrame(tick);
		}

		function onKeyDown(event) {
			if (event.key.toLowerCase() === "r") reset();
			else if (event.key.toLowerCase() === "m") setMuted(!state.muted);
			else if (event.key === " " || event.key === "Enter") {
				event.preventDefault();
				if (state.status === "ready") start();
				else if (state.phase === "inspect" && state.inspected.knob && state.inspected.pointer) setPhase("gears");
			}
		}

		function setMuted(value) {
			state.muted = Boolean(value);
			if (audio) {
				const now = audio.context.currentTime;
				audio.noiseGain.gain.setTargetAtTime(0, now, .03);
				audio.toneGain.gain.setTargetAtTime(state.muted ? 0 : state.phase === "complete" ? .026 : .015 * state.quality, now, .03);
			}
			updateHud();
			return true;
		}

		const api = {
			version: state.version,
			start,
			reset,
			getState: snapshot,
			setStage: (phase) => {
				if (state.status === "ready") start();
				return setPhase(phase);
			},
			showHint,
			setEnabled: (value) => state.enabled = Boolean(value),
			setMuted,
			setSpeed: () => false,
			setNextDestination: (value) => state.nextDestination = value || null,
			toggleTrack: () => {
				if (state.status === "ready") return start();
				if (state.phase === "inspect" && state.inspected.knob && state.inspected.pointer) return setPhase("gears");
				if (state.phase === "tune") {
					const previous = state.coarse;
					state.coarse = clamp(previous + .025, 0, 1);
					state.coarseKnobAngle = normalizeAngle(
						state.coarseKnobAngle + (state.coarse - previous) / TUNING_CONTROLS.coarse.valuePerRadian
					);
					updateTuningAudio();
					return true;
				}
				return false;
			}
		};

		canvas.addEventListener("pointerdown", onPointerDown);
		canvas.addEventListener("pointermove", onPointerMove);
		canvas.addEventListener("pointerup", onPointerUp);
		canvas.addEventListener("pointercancel", onPointerUp);
		window.addEventListener("keydown", onKeyDown);
		window.GearCalibrationGame = api;
		updateHud();
		render(lastFrame);
		frame = window.requestAnimationFrame(tick);
		queueMicrotask(() => emit("GEAR_CALIBRATION_READY"));

		return {
			api,
			destroy() {
				if (destroyed) return;
				destroyed = true;
				window.cancelAnimationFrame(frame);
				if (state.hintTimer) window.clearTimeout(state.hintTimer);
				if (state.phaseTimer) window.clearTimeout(state.phaseTimer);
				window.removeEventListener("keydown", onKeyDown);
				canvas.removeEventListener("pointerdown", onPointerDown);
				canvas.removeEventListener("pointermove", onPointerMove);
				canvas.removeEventListener("pointerup", onPointerUp);
				canvas.removeEventListener("pointercancel", onPointerUp);
				if (audio) {
					try { audio.noise.stop(); audio.tone.stop(); audio.context.close(); } catch (_error) {}
				}
				if (window.GearCalibrationGame === api) delete window.GearCalibrationGame;
				root.replaceChildren();
			}
		};
	}

	window.BeyondWallsMiniGames = window.BeyondWallsMiniGames || {};
	window.BeyondWallsMiniGames.gear = {
		mount(rootElement, options) {
			if (!rootElement) throw new Error("Missing mini-game root: gear");
			const instance = createRadioRepair(rootElement, options);
			return {
				get api() { return instance.api; },
				destroy: instance.destroy
			};
		}
	};
})();
